-- Move image references away from public URLs before making the bucket private.
-- Existing rows keep working through short-lived signed URLs generated by the app.
update public.pets
set photo_url = 'sb://pet-images/' || substring(photo_url from '/storage/v1/object/public/pet-images/(.+)$')
where photo_url like '%/storage/v1/object/public/pet-images/%';

update public.journal_entries
set photo_url = 'sb://pet-images/' || substring(photo_url from '/storage/v1/object/public/pet-images/(.+)$')
where photo_url like '%/storage/v1/object/public/pet-images/%';

update public.health_entries
set photo_url = 'sb://documents/' || substring(photo_url from '/storage/v1/object/public/documents/(.+)$')
where photo_url like '%/storage/v1/object/public/documents/%';

update storage.buckets set public = false where id in ('pet-images', 'documents');

drop policy if exists img_read on storage.objects;
create policy img_read on storage.objects for select to authenticated
  using (
    bucket_id = 'pet-images'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or exists (
        select 1 from public.pets p
        where p.photo_url = 'sb://pet-images/' || name
          and public.pet_role(p.id) is not null
      )
      or exists (
        select 1 from public.journal_entries j
        where j.photo_url = 'sb://pet-images/' || name
          and public.pet_role(j.pet_id) is not null
      )
    )
  );

drop policy if exists img_write on storage.objects;
create policy img_write on storage.objects for insert to authenticated
  with check (bucket_id = 'pet-images' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists img_update on storage.objects;
create policy img_update on storage.objects for update to authenticated
  using (bucket_id = 'pet-images' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'pet-images' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists img_delete on storage.objects;
create policy img_delete on storage.objects for delete to authenticated
  using (bucket_id = 'pet-images' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists docs_read on storage.objects;
create policy docs_read on storage.objects for select to authenticated
  using (
    bucket_id = 'documents'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or exists (
        select 1 from public.health_entries h
        where h.photo_url = 'sb://documents/' || name
          and public.pet_role(h.pet_id) is not null
      )
    )
  );

drop policy if exists docs_owner on storage.objects;
create policy docs_owner on storage.objects for all to authenticated
  using (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text);
